version: "0.2"
language: en
words:
  - bindgen
  - binstall
  - bndy
  - Boolish
  - bugprone
  - chrono
  - codecov
  - consts
  - cppcoreguidelines
  - cstdio
  - cstdlib
  - Doherty
  - endfor
  - endgroup
  - endmacro
  - endwith
  - Falsey
  - fontawesome
  - gitmodules
  - inlinehilite
  - iomanip
  - libc
  - libgit
  - linenums
  - markdownlint
  - maturin
  - mdbook
  - mkdocs
  - msvc
  - napi
  - nonminimal
  - peekable
  - pkgs
  - positionals
  - posix
  - preprocess
  - pybind
  - pyfunction
  - pymdownx
  - pymodule
  - pypa
  - pypi
  - pyproject
  - ratelimit
  - reqwest
  - revparse
  - serde
  - superfences
  - tada
  - tasklist
  - tempdir
  - tempfile
  - twemoji
  - vararg
  - venv
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - target/**
